### ISSUE TITLE
Is it possible to use dwgrep to list source files

### ISSUE THREAD

**Issue by vt-alt** [pmachata/dwgrep#42]
Is it possible to use `dwgrep` to list source files, similar to what `debugedit` extracts from binaries. (I.e. `.debug_line` section entries with directory tables combined with file name tables.)

Can you please provide usage example for this if it's possible?

**Comment by pmachata** [comment]
If you happen to want paths to source modules of the binary:
```
unit root
if (name "/" ?starts) then
  name
else
   "%( @AT_comp_dir %)/%( dup name %)"
```
There's nothing for reading directly `.debug_line`. I have had a TODO item for it since forever, but haven't had time to work on dwgrep, or even design how the feature should look and work.
I guess that a way to get at the data indirectly would be to traverse the DIE tree and look at DW_AT_decl_file, then sort & uniq in shell, like so:
```
$ dwgrep /path/to/the/binary -e 'entry @AT_decl_file' | sort | uniq
```
